### ISSUE TITLE
Object reference exception

### ISSUE THREAD

**Issue by slartifer** [HughJeffner/FFRK-LabMem#130]
Last night, encountered the following exception

03:47:11 System.NullReferenceException: Object reference not set to an instance of an object.
   at FFRK_LabMem.Machines.LabParser.<ParsePainting>d__5.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\LabParser.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFRK_Machines.Machines.MachineController`4.<Consume>d__27.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-Machines\Machines\MachineController.cs:line 126

followed by a sequence of restart attempts and later errors such as

03:48:14 [Lab] Button finding loop for 124.804s
03:48:27 [Adb] matches: 1, closest: 0.9714716
03:50:24 FFRK restart timed out

Before ending in a declared failure.  More context in attached log chunk.

[011222 exception.txt](https://github.com/HughJeffner/FFRK-LabMem/files/7854881/011222.exception.txt)

**Comment by HughJeffner** [comment]
Yeah, I got this sequence too, but slightly different since 6.5+ handles restart loops differently.

Android device was on the play store screen to update FFRK.  When I switched back to FFRK, there was the 'forced update' screen with Dr. Mog and a blue button.  I am guessing they activated some switch in the past 8 hours that forces all clients to update to the newest version if they haven't already.

The exception looks like parsing the response from choosing a painting, and it probably had some kind of data to tell the client to display the Dr. Mog screen instead of the expected painting result.  Not sure if this is worth handling as the bot would just get stuck in a restart loop anyway, but it would get rid of the error message at least.

**Comment by slartifer** [comment]
Whoops.  Device didn't make it to the play store screen so I didn't realize this had happened.  Sorry about that!

**Comment by HughJeffner** [comment]
Where did it get stuck, was it the forced update?

**Comment by slartifer** [comment]
Probably, given the timing -- especially the restart timing out after 1 button-find.  Device was frozen and displaying the launcher when I found it; I suppose it must have failed to open the play store in the last attempt.
