### ISSUE TITLE
No data to read exception

### ISSUE THREAD

**Issue by HughJeffner** [HughJeffner/FFRK-LabMem#210]
> 06:02:58 Picking painting 3: Combatant Painting: Zombie Borghen (Labyrinth) [R]
> 06:03:02 Battle Info
> 06:03:42 Possible hang, attempting recovery!
> 06:03:42 Navigating back
> 06:05:02 Hang detected!
> 06:05:02 Restarting FFRK
> 06:05:03 SharpAdbClient.Exceptions.AdbException: No Data to read: An established connection was aborted by the software in your host machine
>    at SharpAdbClient.AdbSocket.Read(Byte[] data, Int32 length)
>    at SharpAdbClient.AdbSocket.Read(Byte[] data)
>    at SharpAdbClient.AdbSocket.ReadAdbResponseInner()
>    at SharpAdbClient.AdbSocket.ReadAdbResponse()
>    at SharpAdbClient.AdbClient.<ExecuteRemoteCommandAsync>d__35.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at FFRK_Machines.Services.Adb.Adb.<NavigateBack>d__85.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-Machines\Services\Adb\Adb.cs:line 199
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at FFRK_LabMem.Machines.Lab.<Watchdog_Warning>d__90.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\Lab.cs:line 310

**Comment by HughJeffner** [comment]
> 10:13:26 Disabled Lab
> 10:13:26 SharpAdbClient.Exceptions.AdbException: No Data to read: An established connection was aborted by the software in your host machine
>    at SharpAdbClient.AdbSocket.Read(Byte[] data, Int32 length)
>    at SharpAdbClient.AdbSocket.Read(Byte[] data)
>    at SharpAdbClient.AdbSocket.ReadAdbResponseInner()
>    at SharpAdbClient.AdbSocket.ReadAdbResponse()
>    at SharpAdbClient.AdbClient.<ExecuteRemoteCommandAsync>d__35.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at FFRK_Machines.Services.Adb.Adb.<StopPackage>d__86.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-Machines\Services\Adb\Adb.cs:line 208
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at FFRK_LabMem.Machines.Lab.<RestartFFRK>d__32.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\Lab.Actions.cs:line 1059
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at FFRK_LabMem.Machines.Lab.<Watchdog_Timeout>d__89.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\Lab.cs:line 240
