### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by HughJeffner** [HughJeffner/FFRK-LabMem#55]
Stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FFRK_LabMem.Data.DataLogger.<LogBattleDrops>d__6.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Data\DataLogger.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFRK_LabMem.Machines.Lab.<FinishBattle>d__9.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\Lab.Actions.cs:line 444
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFRK_LabMem.Machines.Lab.<<ConfigureStateMachine>b__42_9>d.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\Lab.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.StateRepresentation.<ExecuteEntryActionsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.StateRepresentation.<EnterAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<EnterStateAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<HandleTransitioningTriggerAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireOneAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireQueuedAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stateless.StateMachine`2.<InternalFireAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFRK_LabMem.Machines.Lab.<<RegisterWithProxy>b__44_2>d.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-LabMem\Machines\Lab.cs:line 270
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFRK_Machines.Machines.MachineController`4.<Consume>d__20.MoveNext() in C:\usr\hughjeffner\FFRK-LabMem\FFRK-Machines\Machines\MachineController.cs:line 104
```

**Comment by HughJeffner** [comment]
I lost the tag to the version this came from, stack trace is useless
